spring:
  datasource:
    mapper-location: classpath:/mapper/**/*.xml
    username: root
    password: Admin!@34
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC