spring:
  # DB연동2
  # yml은 이런 방식으로 임포트
  # 설정 파일이 여러개일 경우, 배열 형식으로 가능
  # - db.yml
  # - db2.yml등
  config:
    import: db.yml
#  profiles:
#    include: db
#db:
#  url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC
#  username: root
#  password: Admin!@34
#  driverClassName: com.mysql.cj.jdbc.Driver